### PR TITLE
feat(review): link the build summary with Github

### LINKED ISSUE #129: Link the build summary to GitHub
As a user, I can click on the build summary link and go back to GitHub.

### Motivation

We constantly switch between services, the easier the better.

### Detail

We gonna need to get the repository base url.

### PR DESCRIPTION
**Pull request by oliviertassinari**
Closes #129

### CODE REVIEW

**Comment by neoziro** [comment]
Nice!

**Comment by oliviertassinari** [comment]
😄

**Comment by oliviertassinari** [comment]
For instance https://www.argos-ci.com/doctolib/doctolib/builds/2386.

**Comment by oliviertassinari** [comment]
I'm focusing on https://github.com/argos-ci/argos/issues/165 next. There is 4 area involved:
- settings
- fake build as an example (follow sentry)
- docs page regarding how to push stuff
- build page with an informative message

**Pull request merged**
